---
title: "AI is dangerous not because it will betray humans"
date: "2026-02-07"
date-modified: "2026-02-07"
categories: []
description: "It disrupts power dynamics"
toc: true
draft: true
format:
  html: 
    highlight-style: tango 
---

### Science fiction: AGI betrays humans

This is commonly seen in science fiction movies, and we like them because from the bottom of our hearts, we don't believe they will actually happen.


## But AI is still dangerous

Humanity is fragile.
We are close to extinction ourselves many times in history, and we are still here mostly by luck.

Powerful tools requires advanced wisdom to wield.
Technology is advancing fast, but humanity is not keeping up.

Human society is somewhat balanced today, with complex and fragile power dynamics.

AI produces a crushing amount of disruption by making certain types of task extremely cheap, which will fundamentally change the way we distribute money and power. 
We are not ready for it.

This kind of disruption happens multiple times in history, and we will eventually reach a new equilibrium. 
But the key is to survive the transition period.
As we have more powerful tools, the fluctuation of the transition period will be more violent, so violent that it may wipe out humanity entirely.

In the book "The Better Angels of Our Nature", Steven Pinker argues that violence has declined over time, and humanity is advanced over time.

## The blue pill and red pill

Consider this thought experiment: in front of you are two buttons.

The blue button will advance any technologies we would love to have, nuclear fusion, AGI, cure cancer, etc.
Anything we wanted to have will be instantly available, with no catches.

The red button will explode all nuclear bombs on Earth, wiping out humanity entirely.

Which one would you press?

You may think it's nobrainer to press the blue button, and consider people who press the red button as psychopaths anti-human. 
If you think this way, you're lucky, you have been benefiting from all the best parts of human civilization, good for you! And I genuinely envy you.

As you think deeper, you may realize there might be people who would legitimately press the red button.
Consider the helpless people in Urkaine, consider the innocents killed by ICE, consider people arrested for free speech.

Thinking deeper, you may realize that the most of the miserables in this world are not because lacking technology, but because of the greedy, power-hungry people who are turning the human against each other.
You realized that millions people's misery is just because of a few people in suits playing cards.

Advancing technology is not going to reduce, if not increase, the misery of the human.
If we must solve the problem, the blue button is not going to help.

## Is this world worth living?

Finnally, you may realize, the above experiment is in fact asking this question: 
Is this world worth living? 
The evidence is ambivalent.

