project:
  type: website

website:
  title: "Xiangpeng's blog"
  site-url: https://blog.xiangpeng.systems
  open-graph: true
  twitter-card: true
  search: 
    keyboard-shortcut: ['/']
  navbar:
    right:
      - icon: person-circle
        href: https://xiangpeng.systems
      - icon: github
        href:  https://github.com/XiangpengHao
      - icon: linkedin
        href: https://www.linkedin.com/in/hao-xiangpeng/
      - icon: rss
        href: index.xml

include-in-header: 
  file: cloudflare.html 

format:
  html:
    theme: cosmo
    css: styles.css

resources:
  - CNAME

