---
title: "InfluxData > Google and Microsoft"
date: "2024-08-18"
date-modified: "2024-08-18"
categories: []
toc: true
---

I have interned at Google, Microsoft (Research), and InfluxData. The experience at InfluxData has been the most enjoyable, and this blog post explains why. 

Smaller companies are more **connected** to the real business, more **connected** within the company, and more willing to **connect** you to the rest of the world.


## Problem definition
**Non-problems**

I have worked on great projects: (1) auto-tuned BigTable, (2) designed a new B-Tree system, and (3) [implemented StringView](https://www.youtube.com/watch?v=RVLshX6fbds) in DataFusion.

I have met great people: [Yixin Luo](https://www.cs.cmu.edu/~yixinluo/), [Badrish Chandramouli](https://www.microsoft.com/en-us/research/people/badrishc/), and [Andrew Lamb](http://andrew.nerdnetworks.org).
They are professional and helpful, and I learned a lot from them. 


**The problem**

The problem is *connectivity*: Is the project connected to the real product/customer? Am I connected to the company? Am I visible to the rest of the world?

Big tech has systematic cultural issues that prevent each individual from being connected, and there's no easy way to fix it. 

## Connect to business

I have constantly been reminded to connect my intern project to the InfluxData business -- how it improves InfluxDB3.0, what Influx queries it can accelerate, how it compares with the current approaches, etc.

Andrew expects my project to deploy in production rather than behind a feature gate that no one uses, and he worked very hard to make it happen.
Andrew also reminded me to connect my presentation to InfluxDB3.0 and discuss how the benefits propagate to the product. 

This is an important feeling of real -- I'm not being paid to work on a toy exploration, not a project that requires five extra teams to reach customers. Instead, it is a project grounded by real systems and real needs, and it will be running as part of a real product.

Being real means my time and efforts are respected and valued. Most importantly, it means the investment is sustainable because some kind of return is expected.


## Connect to peers 

Despite being a remote-only company, InfluxData is highly connected: cross-team collaborations, company-wide acknowledgments for great work, and short turn-around for approval.

I only learned to appreciate the above after seeing teams fighting for the same project, achievements downplayed due to politics, and bureaucratic processes blocking individual growth. 

Connecting to peers means working with real people, rather than a faceless bureaucratic system. 
You work towards a shared goal, not a surprise order from high above.
When unexpected happens, you know who to talk to, and
you can reason the consequences by common sense, not with a rule book or guessing what the boss wants.

Being treated as a respected individual, rather than some resource/tool/refillable, is sometimes more important than being paid well.

## Connect to the world

Big techs have trust and ego issues. They develop/control their own programming languages, frameworks, platforms, etc.
They do not sincerely share with the rest of the world, and they design procedures to prevent individuals from doing so.
This means your work is only visible to a small group of people, even if it could have a much broader impact.

At InfluxData, I have seen the opposite. Not only is all of my work open source, but the company is actively helping me share it on the company blog, X, and LinkedIn.
Andrew even took me to a DataFusion meetup and introduced me to the larger FDAP community. (Meanwhile, Microsoft asks students to pay the travel fee to present company work at conferences)

Open source at InfluxData means not simply moving the repo to the public domain but sincerely engaging with the community, cultivating an environment where everyone is welcome to contribute, and making sure the goals and intentions are clear and well-communicated.
As an example, Andrew and I have spent an extensive amount of time writing the blog post and trying our best to share what we have learned with the community, 
while we could have just merged the PR and moved forward.


## What makes a connected culture? 

Small companies don't automatically gain a connected culture, but I can tell that InfluxData and Andrew have made deliberate efforts to make it happen.

Large companies, on the other hand, have systematic issues that prevent this connected culture. Even though every individual I met at Google and Microsoft was nice and kind, 
there's little they can do to fix the problem from the [faceless bureaucratic system](https://en.wikipedia.org/wiki/The_Trial) -- you can't even name a person to blame; it is the procedure.

One of my dreams is to create an employee-first company that prioritizes respect for individuals, explores new ways to organize and connect people, and focuses on maximizing their happiness and creativity rather than just pursuing profit.

(I'd like to thank [Xuanwo](https://xuanwo.io) for encouraging me to finish this blog post!)
