---
title: "Three types of good academic advisors"
date: "2024-05-07"
date-modified: "2024-05-07"
categories: []
toc: true
---


## Good advisors
Entrepreneurs, innovators, and educators.

**Entrepreneur**: good at resource acquisition and allocation. Students have enough resources to reach their potential. They connect people and match the right students with the right resources. Example: [Aditya Akella](https://www.cs.utexas.edu/~akella/).

**Innovator**: good at finding the right thing to do. They have a clear vision of what important problems are. They are often smart people who deeply understand the problems they work on. Students learn a lot about their methodologies, visions, and ways of thinking/reasoning. Example: [Mike Stonebraker](https://en.wikipedia.org/wiki/Michael_Stonebraker).

**Educator**: good at teaching and empowering the students. They empower their student to reach their potential and to find what they are good at. They motivate their students and ignite their passions. Example: [Remzi H. Arpaci-Dusseau](https://pages.cs.wisc.edu/~remzi/)(likely also [Andrea C. Arpaci-Dusseau](https://pages.cs.wisc.edu/~dusseau/), but I haven't worked with her).

A good advisor doesn't necessarily have to be in only one category; for example, I have seen many good educators also be good innovators, but a good advisor often has to be in at least one of the categories. 

I'm privileged enough to have worked with all three types of good advisors; however, finding a good advisor requires a lot of luck and effort.
Reality check: many faculty members (especially in prestigious universities) are not in any of the categories, and most don't even try to be a good advisor.

## Signs of bad advisors
> All happy families are alike; each unhappy family is unhappy in its own way. -- Leo Tolstoy

Like unhappy families, bad advisors are pretty novel in their ways of being bad; we don't summarize them here. 
Instead, we list some key symptoms of working with a bad advisor.


1. **Time-to-recovery**, i.e., how long does it take to recover from a meeting with your advisor?

Regular meetings with your advisor can be stressful; often the time you need to prepare many slides, teach your advisor about your work, and try to get some feedback.
Often, especially in the early stages of your Ph.D., you don't have good presentation/communication skills to explain your work to your advisor. 
Your advisor can get impatient and think you are not progressing or working hard enough.

This can be frustrating and demotivating, and this pattern repeats every week.
The question is, how long does it take to recover from this meeting?
I have experienced that it can take a few hours, or even an entire day, to recover from the frustration and continue to work on my research.
However, it does not have to be this way; a good advisor can motivate students and give concrete feedback to help them improve.

2. **Being treated like a human**, i.e., not a tool/machine to generate papers.

Graduate students are first humans, then students, and then researchers, but never tools/machines to generate papers.

Most bad advisors treat their students as leverage to fulfill their own goals.
They often have very concrete expectations from their students: publish X papers in Y top-tier conferences/journals and work on Z topics with W skill sets.
They evaluate their student by whether they can meet those expectations; even worse, those expectations are often inexplicit and change over time.

If students lag behind expectations -- which happens all the time -- they are often blamed for not working hard enough or not being smart enough.
Worse, they will be threatened to delay graduation, withdraw funding, or even be kicked out of the program.
Even if students are on track, they are often not appreciated for their hard work and dedication.
They are given more work to do, and the cycle repeats.

Graduate study is a long journey; without being treated like a real human, you **feel** suffering, lonely, and lost.
But you deserve a supportive, fruitful, and enjoyable PhD study.

3. **Being aware of power dynamics**, you are my boss.

Many people dreamed an advisor-advisee relationship would be like a marriage partnership: they respect, trust, and work together to achieve common goals.

But that is never the case in reality; we should stop pretending and wake up from that dream.
Advisors pay their students' salaries, and they can decide whether they can graduate or not.
The conversation between an advisor and a student is never equal, and the power dynamics are always there.

The real challenge is whether the advisor is aware of these power dynamics and how they use them.
When in disagreement, does the student have the real freedom to say no? Does the advisor sincerely feel comfortable to be challenged?
Navigating these power dynamics is art for both students and advisors, but it's on the advisors to practice and ensure students feel safe and respected.

## Self-reflections
It's easy to blame bad advisors, but it is hard not to become one.

I suffered a lot from bad advisors, but I often wonder if I can be better than them.
Toxic advisors result from systematic academia problems, and changing the system is hard.
That's why good advisors are rare and worth being recognized and appreciated.

When pressured with tenure, funding, and publication, will I be as nice/patient/motivating/caring as I imagined myself to be?





